export const COPY_TEXT = 'COPY_TEXT';
export const TEXT_COPIED = 'TEXT_COPIED';
export const COPY_BUTTON_HOVERED = 'COPY_BUTTON_HOVERED';
export const EDITOR_CHANGED = 'EDITOR_CHANGED';
export const RENDERURL_CHANGED = 'RENDERURL_CHANGED';
export const DIAGRAM_CHANGED = 'DIAGRAM_CHANGED';
export const DIAGRAM_CHANGED_UPDATE = 'DIAGRAM_CHANGED_UPDATE';
export const DIAGRAM_TYPE_CHANGED = 'DIAGRAM_TYPE_CHANGED';
