export const OPEN_EXAMPLES = 'OPEN_EXAMPLES';
export const CHANGE_EXAMPLE_INDEX = 'CHANGE_EXAMPLE_INDEX';
export const IMPORT_EXAMPLE = 'IMPORT_EXAMPLE';
export const VIEW_EXAMPLE = 'VIEW_EXAMPLE';
export const CLOSE_EXAMPLE = 'CLOSE_EXAMPLE';