export const SAVED='SAVED'
export const SAVING='SAVING'
export const CHANGED='CHANGED'
export const SET_DIAGRAM_SOURCE_STATUS='SET_DIAGRAM_SOURCE_STATUS'
export const SET_DIAGRAM_IMAGE_STATUS='SET_DIAGRAM_IMAGE_STATUS'
export const SET_DIAGRAM_DISK_STATUS='SET_DIAGRAM_DISK_STATUS'
export const DIAGRAM_SOURCE_SAVE_START = 'DIAGRAM_SOURCE_SAVE_START';
export const DIAGRAM_SOURCE_SAVE_END = 'DIAGRAM_SOURCE_SAVE_END';
export const DIAGRAM_SOURCE_SAVE_FAIL = 'DIAGRAM_SOURCE_SAVE_FAIL';
export const DIAGRAM_IMAGE_GET_START = 'DIAGRAM_IMAGE_GET_START';
export const DIAGRAM_IMAGE_GET_END = 'DIAGRAM_IMAGE_GET_END';
export const DIAGRAM_IMAGE_GET_FAIL = 'DIAGRAM_IMAGE_GET_FAIL';
export const DIAGRAM_IMAGE_SAVE_START = 'DIAGRAM_IMAGE_SAVE_START';
export const DIAGRAM_IMAGE_SAVE_END = 'DIAGRAM_IMAGE_SAVE_END';
export const DIAGRAM_IMAGE_SAVE_FAIL = 'DIAGRAM_IMAGE_SAVE_FAIL';
export const SET_FILE = 'SET_FILE';
export const DIAGRAM_SOURCE_READ = 'DIAGRAM_SOURCE_READ';

